# Site settings
title: thinking out LOUD
description: "my space for the random things in life"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-93754325-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
disqus_url: taherchhabra.github.io
disqus_id: taherchhabra
# register on feedburner and replace this url. Deleting the value will remove it from footer.
feedburner_url: http://feeds.feedburner.com/taherchhabra

# footer details. Deleting the value would remove it from footer.
github_username:  taherchhabra
facebook_username:  taherchhabra
email: taherchhabra@gmail.com
stackoverflow_username: 197876/taher-chhabrawala
twitter_username : taherchhabra
copyright_name: Taher Chhabrawala
rss : true

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
